name: Deploy to Miao Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build:site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
