name: Deploy to Miao Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-14

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
         ref: 'main'

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'


      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build:site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: dist/site
          token: ${{ secrets.MIAO_UI_TOKEN }}
