name: Deploy site

on:
  push:
    branches:
      - main # 监听 main 分支推送

permissions:
  contents: write # 允许 GitHub Actions 推送到 gh-pages 分支

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm' # 使用 pnpm 缓存

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # 确保 pnpm 版本正确

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build:site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/site
